//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stroymateriali.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id_orders { get; set; }
        public int orders_pointup { get; set; }
        public int orders_users { get; set; }
        public int orders_check { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual Pointup Pointup { get; set; }
        public virtual Users Users { get; set; }
    }
}
